# Site settings
title: Receptari
email: correuperamerda@hotmail.com
description: The plain text recipe database for Carminas
baseurl: "https://lamevacuina.github.io/receptari"
github_username: lamevacuina

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
